[package]
name = "graph-runtime-derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.48", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.73"
heck = "0.4"
