version: "3"
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - "8000:8000"
    environment:
      postgres_host: "64.227.79.177" # IP of your centralized PostgreSQL
      postgres_user: "graph-node"
      postgres_pass: "let-me-in"
      postgres_db: "graph-node"
      ipfs: "64.227.79.177:5001" # IP of your centralized IPFS node
      ethereum: "mainnet:https://rpc.testnet.lukso.gateway.fm"
      GRAPH_LOG: "info"
      node_role: "query-node"
